import {parseStatement} from './parser.js';
import {makeWorkbook} from './xlsx.js';
const $=id=>document.getElementById(id), statements=[];
function render(){const active=statements[Number($('statement').value)||0];$('workspace').classList.toggle('hidden',!statements.length);if(!active)return;
 $('total').textContent=`${statements.reduce((n,s)=>n+s.rows.length,0).toLocaleString()} rows`;
 $('summary').textContent=`${statements.length} file${statements.length===1?'':'s'} · ${active.type}${active.member?' · '+active.member:''}${active.account?' · '+active.account:''}`;
 $('notice').classList.toggle('hidden',!statements.some(s=>s.skipped.length));$('notice').textContent=statements.filter(s=>s.skipped.length).map(s=>`${s.filename}: ${s.skipped.length} dated line(s) could not be parsed (source lines ${s.skipped.slice(0,15).join(', ')}${s.skipped.length>15?', …':''}).`).join(' ');
 const query=$('search').value.toLowerCase().trim();const body=$('entries');body.replaceChildren();const fragment=document.createDocumentFragment();const keys=['section','date','reference','document','particulars','debit','credit','balance','side'];
 active.rows.forEach((row,index)=>{if(query&&!['section','date','reference','document','particulars','balance'].some(key=>String(row[key]??'').toLowerCase().includes(query)))return;const tr=document.createElement('tr');for(const key of keys){const td=document.createElement('td'),input=document.createElement('input');input.setAttribute('aria-label',`${key} row ${index+1}`);input.value=row[key]??'';input.dataset.index=index;input.dataset.key=key;if(['debit','credit','balance'].includes(key)){input.type='number';input.step='0.01';input.min='0';}td.append(input);tr.append(td);}const td=document.createElement('td');td.textContent=row.line;tr.append(td);fragment.append(tr);});body.append(fragment);
}
$('entries').addEventListener('change',event=>{const input=event.target;if(!input.dataset.key)return;const row=statements[Number($('statement').value)].rows[Number(input.dataset.index)],key=input.dataset.key;if(['debit','credit','balance'].includes(key)){if(input.value!==''&&(!Number.isFinite(Number(input.value))||Number(input.value)<0)){input.value=row[key]??'';return;}row[key]=input.value===''?null:Number(input.value);}else row[key]=input.value;});
$('files').addEventListener('change',event=>load(event.target.files));$('statement').addEventListener('change',render);$('search').addEventListener('input',render);$('clear').addEventListener('click',()=>{statements.length=0;$('statement').replaceChildren();$('files').value='';$('search').value='';render();});
async function load(files){const problems=[];for(const file of files){try{if(!/\.txt$/i.test(file.name))throw new Error('Choose a .txt file');const parsed=parseStatement(await file.text(),file.name);if(!parsed.rows.length)throw new Error('No statement entries found');statements.push(parsed);const option=document.createElement('option');option.value=String(statements.length-1);option.textContent=`${file.name} (${parsed.rows.length} rows)`;$('statement').append(option);}catch(error){problems.push(`${file.name}: ${error.message}`);}}if(statements.length)$('statement').value=String(statements.length-1);render();if(problems.length)alert(problems.join('\n'));}
const drop=$('drop');for(const type of ['dragenter','dragover'])drop.addEventListener(type,event=>{event.preventDefault();drop.classList.add('drag');});for(const type of ['dragleave','drop'])drop.addEventListener(type,event=>{event.preventDefault();drop.classList.remove('drag');});drop.addEventListener('drop',event=>load(event.dataTransfer.files));
$('export').addEventListener('click',()=>{if(!statements.length)return;const blob=makeWorkbook(statements),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`uzima-statements-${new Date().toISOString().slice(0,10)}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);});
