// Small dependency-free XLSX writer: one worksheet per uploaded statement.
const encoder = new TextEncoder();
const xml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');
const crcTable = Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++) n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(bytes){let n=-1; for(const b of bytes)n=crcTable[(n^b)&255]^(n>>>8);return (n^-1)>>>0;}
function zip(entries){let offset=0;const chunks=[],directory=[];const u16=n=>[n&255,n>>>8&255],u32=n=>[n&255,n>>>8&255,n>>>16&255,n>>>24&255];
  for(const [path,data] of entries){const name=encoder.encode(path),body=encoder.encode(data),crc=crc32(body);const local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(body.length),...u32(body.length),...u16(name.length),...u16(0),...name]);chunks.push(local,body);directory.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(body.length),...u32(body.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]));offset+=local.length+body.length;}
  const size=directory.reduce((n,d)=>n+d.length,0);const footer=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(directory.length),...u16(directory.length),...u32(size),...u32(offset),...u16(0)]);return new Blob([...chunks,...directory,footer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
const headings=['Section','Date','Reference','Document','Cheque','Particulars','Debit','Credit','Balance','Dr/Cr','Source line'];
const keys=['section','date','reference','document','cheque','particulars','debit','credit','balance','side','line'];
function sheet(rows){const body=[headings,...rows.map(row=>keys.map(key=>row[key]))];return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols><col min="1" max="1" width="27" customWidth="1"/><col min="2" max="6" width="19" customWidth="1"/><col min="7" max="9" width="18" customWidth="1"/></cols><sheetData>${body.map((row,i)=>`<row r="${i+1}">${row.map((value,j)=>{if(value===null||value===undefined||value==='')return '';const col=String.fromCharCode(65+j);return typeof value==='number'?`<c r="${col}${i+1}"${j>=6&&j<=8?' s="1"':''}><v>${value}</v></c>`:`<c r="${col}${i+1}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`;}).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:K${body.length}"/></worksheet>`;}
export function makeWorkbook(statements){const used=new Set();const names=statements.map((statement,i)=>{let base=(statement.filename.replace(/\.[^.]+$/,'').replace(/[\\/?*\[\]:]/g,'_').slice(0,25)||`Sheet ${i+1}`),name=base,j=2;while(used.has(name.toLowerCase()))name=`${base.slice(0,26-String(j).length)}_${j++}`;used.add(name.toLowerCase());return name;});
const entries=[['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${names.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${names.map((name,i)=>`<sheet name="${xml(name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],['xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${names.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${names.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`],['xl/styles.xml','<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.00"/></numFmts><fonts count="1"><font><sz val="11"/><name val="Aptos"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" xfId="0"/><xf numFmtId="164" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>']];statements.forEach((s,i)=>entries.push([`xl/worksheets/sheet${i+1}.xml`,sheet(s.rows)]));return zip(entries);}
